// <auto-generated />
namespace StackOverflow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateagain));
        
        string IMigrationMetadata.Id
        {
            get { return "201705010032082_updateagain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
